export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const PLAYER_USER_REQUEST = "PLAYER_USER_REQUEST";
export const PLAYER_USER_SUCCESS = "PLAYER_USER_SUCCESS";
export const PLAYER_USER_FAILED = "PLAYER_USER_FAILED";

export const ADD_PLAYER_REQUEST = "ADD_PLAYER_REQUEST";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_FAILED = "ADD_PLAYER_FAILED";

export const UPDATE_PLAYER_REQUEST = "UPDATE_PLAYER_REQUEST";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_FAILED = "UPDATE_PLAYER_FAILED";

//admin
export const LIST_PLAYER_REQUEST = "LIST_PLAYER_REQUEST";
export const LIST_PLAYER_SUCCESS = "LIST_PLAYER_SUCCESS";
export const LIST_PLAYER_FAILED = "LIST_PLAYER_FAILED";

export const INFO_PLAYER_REQUEST = "INFO_PLAYER_REQUEST";
export const INFO_PLAYER_SUCCESS = "INFO_PLAYER_SUCCESS";
export const INFO_PLAYER_FAILED = "INFO_PLAYER_FAILED";
